baseURL: https://cronohub.org/
languageCode: en-us
title: Welcome to Cronohub
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Archive from anywhere, to anywhere.
    # Hero subtitle (optional)
    subtitle: Archiving made easy via highly configurable plugins.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from /images/___)
    image: illustrations/crono_logo.png
    # Footer logos (from /images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Plugin
    url: /plugin
  section1:
    title: Flexibility through
    subtitle: plugins
    tiles:
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: Writing your own
    subtitle: plugin
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
  section4:
    title: Contributions
    clients:
    - name: Github
      quote: https://github.com/cronohub 
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/cronohub
      # Icons are from Font Awesome
      icon: github
